spring.application.name=recurly-billing

# DATABASE
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#YOOKASSA
yookassa.shop-id=${SHOP_ID}
yookassa.secret-key=${SECRET_KEY}
yookassa.api-url=${API_URL}